openapi: 3.0.0
x-stoplight:
  id: xan49ielb77h4
info:
  title: Template API
  version: '1.0'
  description: The Template API allows the management of templates withing RapidCX.
  contact:
    name: Colin Kirkham
    url: 'https://www.precisely.com'
    email: colin.kirkham@precisely.com
  license:
    name: Proprietary
    url: 'https://www.precisely.com'
servers:
  - url: 'http://localhost:3000'
    description: Colin Kirkham
paths:
  '/templates/{id}':
    get:
      summary: Get Template
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Template'
      operationId: get-template
      description: 'Get a single, existing template.'
      parameters:
        - $ref: '#/components/parameters/Tenant-ID'
    parameters:
      - schema:
          type: string
          format: uuid
        name: id
        in: path
        required: true
        description: The ID of the template to retrieve
    put:
      summary: ''
      operationId: update-template
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Template'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Template'
      description: Update an existing template.
      parameters:
        - $ref: '#/components/parameters/Tenant-ID'
    delete:
      summary: ''
      operationId: delete-template
      responses:
        '200':
          description: OK
      description: Delete an existing template
      parameters:
        - $ref: '#/components/parameters/Tenant-ID'
  /templates:
    get:
      summary: Get Template
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Template'
                  x-stoplight:
                    id: hmy64zb7yv6iy
      operationId: get-all-templates
      description: Get all templates.
      parameters:
        - $ref: '#/components/parameters/Tenant-ID'
    parameters: []
    post:
      summary: ''
      operationId: create-template
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Template'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Template'
      description: Create a new template.
      parameters:
        - $ref: '#/components/parameters/Tenant-ID'
components:
  schemas:
    Template:
      title: Template
      x-stoplight:
        id: j8cx7yix0y9y2
      type: object
      description: Standard model of a template.
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        name:
          type: string
          x-stoplight:
            id: ta9nckeguj46s
        content:
          type: string
          x-stoplight:
            id: c7ka58rc34x9p
  parameters:
    Tenant-ID:
      name: Tenant-ID
      in: header
      required: false
      schema:
        type: string
      description: The tenant for the request
tags:
  - name: rapidcx
    description: Related to the RapidCX project.
  - name: template
    description: Template related capabilities
